image: node:latest

  stages:
    - build
    - run

  cache:
    paths:
      - node_modules/

  build:
    stage: build
    script:
      - yarn
      - yarn global add typescript
      - tsc *.ts /build
      - ls
    artifacts:
      paths:
        - node_modules/
        - build/

  run:
    stage: run
    script: yarn run start
